version: '3'
services:
  tfip-miniproject:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      # - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      # - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - JWT_SIGNINGKEY=${JWT_SIGNINGKEY}