spring:
  # Database connection properties
  datasource:
    # We may omit any property provided by docker-compose.yml, since it will be overridden
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect