spring:
  # Database connection properties
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/tfip_miniproject
    username: ${MYSQL_USER:sha2user}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  signingkey: ${JWT_SIGNINGKEY}