spring:
  # Database connection properties
  datasource:
    url: jdbc:mysql://localhost:3306/tfip_miniproject
    username: ${MYSQL_USER:sha2user}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: 
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect