spring:
  # Database connection properties
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ${MONGODB_URI}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  signingkey: ${JWT_SIGNINGKEY}

# For Railway
# server:
#   address: 0.0.0.0
#   port: ${PORT:8080}