apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-backend-deployment
  labels:
    app: sb-backend
spec:
  selector:
    matchLabels:
      app: sb-backend
  template:
    metadata:
      labels:
        app: sb-backend
    spec:
      containers:
      - name: sb-backend
        # image: echarin/sb-backend
        image: gcr.io/${PROJECT_ID}/${BACKEND_IMAGE}:${TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: mysql-url
          - name: SPRING_DATA_MONGODB_URI
            valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mongodb-uri
          - name: JWT_SIGNINGKEY
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: jwt-signing-key
        livenessProbe:
          httpGet:
            path: "/liveness-check"
            port: 8080
          initialDelaySeconds: 40
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: "/readiness-check"
            port: 8080
          initialDelaySeconds: 40
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: "/startup-check"
            port: 8080
          initialDelaySeconds: 40
          

---

apiVersion: v1
kind: Service
metadata:
  name: sb-backend-service
  labels:
    app: sb-backend
spec:
  # Default type is ClusterIP
  selector:
    app: sb-backend
  ports:
  - port: 8080
    targetPort: 8080