name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
    paths:
      - 'sb-backend/**'
      - 'ng-frontend/**'
      - 'k8s/**'

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: tfip-miniproject
  GKE_ZONE: asia-southeast1-a
  DEPLOYMENT_NAME: tfip-miniproject
  BACKEND_IMAGE: sb-backend-image
  FRONTEND_IMAGE: ng-frontend-image
  TAG: ${{ github.sha }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, Deploy
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
          
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          version: 'latest'
          project_id: ${{ secrets.PROJECT_ID }}
          
      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
          
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          
      - name: Build Docker images
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$TAG" ./ng-frontend/
          docker build --tag "gcr.io/$PROJECT_ID/$BACKEND_IMAGE:$TAG" ./sb-backend/
      
      - name: Push Docker images to Google Container Registry
        run: |-
          docker push "gcr.io/$PROJECT_ID/$FRONTEND_IMAGE:$TAG"
          docker push "gcr.io/$PROJECT_ID/$BACKEND_IMAGE:$TAG"

      - name: Substitute image names in deployment manifests
        run: |-
          envsubst < ./k8s/sb-backend-template.yaml > ./k8s/sb-backend.yaml
          envsubst < ./k8s/ng-frontend-template.yaml > ./k8s/ng-frontend.yaml
    
      - name: Deploy to GKE
        run: |-
          kubectl apply -f ./k8s/sb-backend.yaml
          kubectl apply -f ./k8s/ng-frontend.yaml
          kubectl apply -f ./k8s/app-ingress.yaml
        # kubectl apply -f ./k8s/sb-ingress.yaml
        # kubectl apply -f ./k8s/ng-ingress.yaml

