name: Deploy Spring Boot backend to Railway

on:
  push:
    branches:
      - main
    paths:
      - 'sb-backend/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Railway
        uses: npm i -g @railway/cli
      
      - name: Deploy to Railway
        run: railway up
        working-directory: sb-backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}